// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Arg = require("arg");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Config$BfarmisenBranchName = require("./Config.bs.js");

function parseArgs(param) {
  var parameters = ({
    '--id': String,
    '--project': String,
    '--help': Boolean,
    '--doc': Boolean,
    '--config': String,
    '-i': '--id',
    '-p': '--project',
    '-h': '--help',
    '-d': '--doc'
});
  var parsed = Arg(parameters);
  if (Belt_Option.getWithDefault(parsed["--doc"], false)) {
    return /* Doc */0;
  }
  var match = parsed["--id"];
  var match$1 = parsed["--project"];
  if (match === undefined) {
    if (match$1 !== undefined) {
      return {
              TAG: /* Help */1,
              _0: "Missing project"
            };
    } else {
      return {
              TAG: /* Help */1,
              _0: undefined
            };
    }
  }
  if (match$1 === undefined) {
    return {
            TAG: /* Help */1,
            _0: "Missing issue id"
          };
  }
  var config = Config$BfarmisenBranchName.projectConfig(Caml_option.valFromOption(match$1), parsed["--config"]);
  if (config.TAG) {
    return {
            TAG: /* Help */1,
            _0: config._0
          };
  } else {
    return {
            TAG: /* NameBranch */0,
            _0: Caml_option.valFromOption(match),
            _1: config._0
          };
  }
}

exports.parseArgs = parseArgs;
/* arg Not a pure module */
