// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Arg = require("arg");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Config$BranchName = require("./Config.bs.js");

function parseArgs(param) {
  var parameters = ({
    '--id': String,
    '--project': String,
    '--list': Boolean,
    '--create': Boolean,
    '-i': '--id',
    '-p': '--project'
});
  var result = Arg(parameters);
  if (result["--list"]) {
    return /* ListProjects */0;
  }
  if (result["--create"]) {
    return /* CreateProject */1;
  }
  var config = Config$BranchName.projectConfig(result["--project"]);
  var projectConfig = config !== undefined ? config : Pervasives.failwith("Error reading the project config");
  return /* NameBranch */{
          _0: result["--id"],
          _1: projectConfig
        };
}

exports.parseArgs = parseArgs;
/* arg Not a pure module */
