// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ClubhouseLib = require("clubhouse-lib");

function create(token) {
  return ClubhouseLib.default.create(token);
}

function getStory(id, client) {
  return client.getStory(id);
}

var Bindings = {
  create: create,
  getStory: getStory
};

function getStoryName(id, authToken) {
  return ClubhouseLib.default.create(authToken).getStory(id).then(function (story) {
                return Promise.resolve({
                            TAG: /* Ok */0,
                            _0: story.name
                          });
              }).catch(function (_err) {
              return Promise.resolve({
                          TAG: /* Error */1,
                          _0: "failed while fetching the story"
                        });
            });
}

exports.Bindings = Bindings;
exports.getStoryName = getStoryName;
/* clubhouse-lib Not a pure module */
