// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var ConfigJs = require("./config.js");

var config = ConfigJs.default;

var projects = $$Array.to_list(config.projects);

function projectConfig(projectSlug) {
  try {
    return List.find((function (p) {
                  return p.slug === projectSlug;
                }), projects);
  }
  catch (exn){
    return ;
  }
}

exports.config = config;
exports.projects = projects;
exports.projectConfig = projectConfig;
/* config Not a pure module */
