// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function readSync(path, encoding, flag) {
  return Caml_option.nullable_to_opt(Fs.readFileSync(path, {
                  encoding: encoding,
                  flag: flag
                }));
}

exports.readSync = readSync;
/* fs Not a pure module */
