// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var JiraClient = require("jira-client");

function findIssue(id, client) {
  return client.findIssue(id);
}

var Bindings = {
  findIssue: findIssue
};

function getStoryName(id, host, username, password) {
  return new JiraClient({
                    protocol: "https",
                    host: host,
                    username: username,
                    password: password,
                    strictSSL: true
                  }).findIssue(id).then(function (issue) {
                return Promise.resolve({
                            TAG: /* Ok */0,
                            _0: issue.fields.summary
                          });
              }).catch(function (_err) {
              return Promise.resolve({
                          TAG: /* Error */1,
                          _0: "failed while fetching the story"
                        });
            });
}

exports.Bindings = Bindings;
exports.getStoryName = getStoryName;
/* jira-client Not a pure module */
