// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function defaultformatter(id, name) {
  return id + ("-" + name);
}

function defaultSanitizer(title) {
  return $$String.lowercase_ascii(title).replace(/[\s:\/\[\]{}()_"]/g, "-").replace(/--*/g, "-");
}

function withDefault(value, $$default) {
  return Belt_Option.mapWithDefault(value, $$default, (function (x) {
                return x;
              }));
}

function make(id, name, config) {
  return Curry._2(Belt_Option.mapWithDefault(config.formatter, defaultformatter, (function (x) {
                    return x;
                  })), id, Curry._1(Belt_Option.mapWithDefault(config.sanitizer, defaultSanitizer, (function (x) {
                          return x;
                        })), name).replace(/-/g, Belt_Option.mapWithDefault(config.separator, "-", (function (x) {
                        return x;
                      }))));
}

exports.defaultformatter = defaultformatter;
exports.defaultSanitizer = defaultSanitizer;
exports.withDefault = withDefault;
exports.make = make;
/* No side effect */
