// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");

function defaultTransformer(id, name) {
  return id + ("-" + name);
}

function defaultSanitizer(title) {
  return $$String.lowercase(title).replace(/[\s:\/\[\]{}()"]/g, "-").replace(/--*/g, "-");
}

function make(id, name, config) {
  var transformer = config.transformer;
  var pattern = transformer !== undefined ? transformer : defaultTransformer;
  var sanitizer = config.sanitizer;
  var sanitizer$1 = sanitizer !== undefined ? sanitizer : defaultSanitizer;
  return Curry._2(pattern, id, Curry._1(sanitizer$1, name));
}

exports.defaultTransformer = defaultTransformer;
exports.defaultSanitizer = defaultSanitizer;
exports.make = make;
/* No side effect */
